### ISSUE TITLE
changes to readme

### ISSUE THREAD

**Issue by Adi-Abhishek** [hackbeats/python-bootcamp#21]
I want to give a new look to readme

**Comment by hackbeatsorg** [comment]
ok

**Comment by BTANISHA11** [comment]
i want to work on readme file
adding how to contribute
how to make a pull request 
how to create an issue
can you pls assign this to me @hackbeatsorg

**Comment by Adi-Abhishek** [comment]
[https://github.com/hackbeats/python-bootcamp/commit/da1bcd44a6dcbcd3f40c46e0239b8ae8039697f3](url)

**Comment by Adi-Abhishek** [comment]
#28  changes made

**Comment by kumar-kalyan** [comment]
@BTANISHA11 Go ahead
